FROM golang:1.12-stretch as BUILD

WORKDIR /go/src/github.com/ovh/cds

RUN apt-get update \
    && apt-get install -y libsecret-1-dev
# separating for quicker build times since its for dev

COPY . .

RUN OS=linux ARCH=amd64 make build \
    && rm -rf /var/lib/apt/lists/*

FROM debian:jessie

USER nobody
WORKDIR /app

COPY --from=BUILD --chown=nobody:nogroup /go/src/github.com/ovh/cds/engine/dist/* ./
COPY --from=BUILD --chown=nobody:nogroup /go/src/github.com/ovh/cds/engine/worker/dist/* ./
COPY --from=BUILD --chown=nobody:nogroup /go/src/github.com/ovh/cds/cli/cdsctl/dist/* ./
COPY --chown=nobody:nogroup engine/sql sql

CMD ["/app/cds-engine-linux-amd64"]
