package-name: "cds-engine"
architecture: "amd64"
binary-file: "cds-engine-linux-amd64"
configuration-files:
  - "config.toml.sample"
copy-files:
  - "cds-engine-*"
  - "cdsctl-*"
  - "cds-worker-*"
  - "cds-linux-amd64"
  - "sql.tar.gz"
mkdirs:
  - "/keys"
  - "/artifacts"
version: "{{.cds.semver}}"
description: "Enterprise-Grade Continuous Delivery and DevOps Automation Open Source Platform"
maintainer: "OVH <github@ovh.net>"
systemd-configuration:
  after: network.target
  args: 
    - "start"
    - "${CDS_SERVICE}"
    - "--config"
    - "/etc/cds-engine/cds-engine.toml"
  stop-command: /bin/kill $MAINPID
  restart: always
  wanted-by: multi-user.target
  environments: 
    CDS_SERVICE: "api vcs hooks repositories"
