// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integrationplugin.proto

package integrationplugin

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntegrationPluginManifest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegrationPluginManifest) Reset()         { *m = IntegrationPluginManifest{} }
func (m *IntegrationPluginManifest) String() string { return proto.CompactTextString(m) }
func (*IntegrationPluginManifest) ProtoMessage()    {}
func (*IntegrationPluginManifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad20155c873eed76, []int{0}
}

func (m *IntegrationPluginManifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationPluginManifest.Unmarshal(m, b)
}
func (m *IntegrationPluginManifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationPluginManifest.Marshal(b, m, deterministic)
}
func (m *IntegrationPluginManifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationPluginManifest.Merge(m, src)
}
func (m *IntegrationPluginManifest) XXX_Size() int {
	return xxx_messageInfo_IntegrationPluginManifest.Size(m)
}
func (m *IntegrationPluginManifest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationPluginManifest.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationPluginManifest proto.InternalMessageInfo

func (m *IntegrationPluginManifest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IntegrationPluginManifest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *IntegrationPluginManifest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IntegrationPluginManifest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type DeployQuery struct {
	Options              map[string]string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployQuery) Reset()         { *m = DeployQuery{} }
func (m *DeployQuery) String() string { return proto.CompactTextString(m) }
func (*DeployQuery) ProtoMessage()    {}
func (*DeployQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad20155c873eed76, []int{1}
}

func (m *DeployQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployQuery.Unmarshal(m, b)
}
func (m *DeployQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployQuery.Marshal(b, m, deterministic)
}
func (m *DeployQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployQuery.Merge(m, src)
}
func (m *DeployQuery) XXX_Size() int {
	return xxx_messageInfo_DeployQuery.Size(m)
}
func (m *DeployQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DeployQuery proto.InternalMessageInfo

func (m *DeployQuery) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

type DeployResult struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResult) Reset()         { *m = DeployResult{} }
func (m *DeployResult) String() string { return proto.CompactTextString(m) }
func (*DeployResult) ProtoMessage()    {}
func (*DeployResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad20155c873eed76, []int{2}
}

func (m *DeployResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResult.Unmarshal(m, b)
}
func (m *DeployResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResult.Marshal(b, m, deterministic)
}
func (m *DeployResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResult.Merge(m, src)
}
func (m *DeployResult) XXX_Size() int {
	return xxx_messageInfo_DeployResult.Size(m)
}
func (m *DeployResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResult proto.InternalMessageInfo

func (m *DeployResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeployResult) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type DeployStatusQuery struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployStatusQuery) Reset()         { *m = DeployStatusQuery{} }
func (m *DeployStatusQuery) String() string { return proto.CompactTextString(m) }
func (*DeployStatusQuery) ProtoMessage()    {}
func (*DeployStatusQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad20155c873eed76, []int{3}
}

func (m *DeployStatusQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployStatusQuery.Unmarshal(m, b)
}
func (m *DeployStatusQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployStatusQuery.Marshal(b, m, deterministic)
}
func (m *DeployStatusQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployStatusQuery.Merge(m, src)
}
func (m *DeployStatusQuery) XXX_Size() int {
	return xxx_messageInfo_DeployStatusQuery.Size(m)
}
func (m *DeployStatusQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployStatusQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DeployStatusQuery proto.InternalMessageInfo

func (m *DeployStatusQuery) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*IntegrationPluginManifest)(nil), "integrationplugin.IntegrationPluginManifest")
	proto.RegisterType((*DeployQuery)(nil), "integrationplugin.DeployQuery")
	proto.RegisterMapType((map[string]string)(nil), "integrationplugin.DeployQuery.OptionsEntry")
	proto.RegisterType((*DeployResult)(nil), "integrationplugin.DeployResult")
	proto.RegisterType((*DeployStatusQuery)(nil), "integrationplugin.DeployStatusQuery")
}

func init() { proto.RegisterFile("integrationplugin.proto", fileDescriptor_ad20155c873eed76) }

var fileDescriptor_ad20155c873eed76 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x8b, 0xda, 0x40,
	0x1c, 0x35, 0xd1, 0x6a, 0xfb, 0x53, 0x4a, 0x1d, 0x8a, 0x4d, 0x53, 0x68, 0x25, 0xed, 0x41, 0xa8,
	0x8c, 0x60, 0x2f, 0xe2, 0xa9, 0x88, 0x1e, 0xa4, 0x94, 0xda, 0x78, 0x28, 0xb4, 0xa7, 0x98, 0x8c,
	0x31, 0x18, 0x33, 0x61, 0x66, 0x22, 0xe4, 0xdc, 0x2f, 0xb0, 0xdf, 0x6a, 0xbf, 0xd6, 0x92, 0x99,
	0xc9, 0x6e, 0x20, 0x9b, 0x65, 0x6f, 0xf9, 0xfd, 0x79, 0xef, 0x37, 0xef, 0x3d, 0x02, 0xef, 0xa2,
	0x44, 0x90, 0x90, 0x79, 0x22, 0xa2, 0x49, 0x1a, 0x67, 0x61, 0x94, 0xe0, 0x94, 0x51, 0x41, 0xd1,
	0xb0, 0x36, 0xb0, 0x3f, 0x84, 0x94, 0x86, 0x31, 0x99, 0xc9, 0x85, 0x43, 0x76, 0x9c, 0x91, 0x4b,
	0x2a, 0x72, 0xb5, 0xef, 0xfc, 0x37, 0xe0, 0xfd, 0xf6, 0x01, 0xb2, 0x93, 0x90, 0x9f, 0x5e, 0x12,
	0x1d, 0x09, 0x17, 0x08, 0x41, 0x27, 0xf1, 0x2e, 0xc4, 0x32, 0xc6, 0xc6, 0xe4, 0x95, 0x2b, 0xbf,
	0x91, 0x05, 0xbd, 0x2b, 0x61, 0x3c, 0xa2, 0x89, 0x65, 0xca, 0x76, 0x59, 0xa2, 0x31, 0xf4, 0x03,
	0xc2, 0x7d, 0x16, 0xa5, 0x05, 0x95, 0xd5, 0x96, 0xd3, 0x6a, 0x0b, 0x8d, 0xa0, 0xeb, 0x65, 0xe2,
	0x44, 0x99, 0xd5, 0x91, 0x43, 0x5d, 0x39, 0x37, 0x06, 0xf4, 0xd7, 0x24, 0x8d, 0x69, 0xfe, 0x3b,
	0x23, 0x2c, 0x47, 0x1b, 0xe8, 0x51, 0x89, 0xe0, 0x96, 0x31, 0x6e, 0x4f, 0xfa, 0xf3, 0xaf, 0xb8,
	0x2e, 0xb8, 0x02, 0xc0, 0xbf, 0xd4, 0xf6, 0x26, 0x11, 0x2c, 0x77, 0x4b, 0xac, 0xbd, 0x84, 0x41,
	0x75, 0x80, 0xde, 0x40, 0xfb, 0x4c, 0x72, 0xad, 0xa6, 0xf8, 0x44, 0x6f, 0xe1, 0xc5, 0xd5, 0x8b,
	0x33, 0xa2, 0xa5, 0xa8, 0x62, 0x69, 0x2e, 0x0c, 0xe7, 0x3b, 0x0c, 0xd4, 0x01, 0x97, 0xf0, 0x2c,
	0x16, 0xc5, 0xd3, 0xb9, 0xf0, 0x44, 0xc6, 0x35, 0x5c, 0x57, 0x85, 0x1d, 0x01, 0x11, 0x5e, 0x14,
	0xf3, 0xd2, 0x0e, 0x5d, 0x3a, 0x9f, 0x61, 0xa8, 0x18, 0xf6, 0x72, 0x53, 0x29, 0x7b, 0x0d, 0xe6,
	0x76, 0xad, 0x29, 0xcc, 0xed, 0x7a, 0x7e, 0x6b, 0xc2, 0xb0, 0xe6, 0x3f, 0x72, 0xe1, 0xe5, 0x7d,
	0x06, 0x23, 0xac, 0xf2, 0xc3, 0x65, 0x7e, 0x78, 0x53, 0xe4, 0x67, 0x4f, 0x1f, 0xb1, 0xa4, 0x31,
	0x49, 0xa7, 0x85, 0x7e, 0x40, 0x57, 0x3d, 0x07, 0x7d, 0x7c, 0xda, 0x4c, 0xfb, 0x53, 0xe3, 0x5c,
	0x79, 0xe1, 0xb4, 0xd0, 0x9f, 0xd2, 0x1d, 0xa5, 0x0d, 0x7d, 0x69, 0x84, 0x54, 0xc4, 0x3f, 0x87,
	0x78, 0x01, 0x9d, 0xbd, 0xa0, 0x69, 0xa3, 0xea, 0x86, 0xbe, 0xd3, 0x5a, 0xfd, 0x83, 0xa9, 0x4f,
	0x2f, 0x98, 0x5e, 0x4f, 0xd8, 0x0f, 0x38, 0xe6, 0xc1, 0x19, 0x87, 0x2c, 0xf5, 0xf5, 0x99, 0xda,
	0xe1, 0xd5, 0xa8, 0x66, 0xd6, 0xae, 0xa0, 0xdc, 0x19, 0x7f, 0xeb, 0xff, 0xd0, 0xa1, 0x2b, 0xcf,
	0x7d, 0xbb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x04, 0xbd, 0x83, 0x33, 0x78, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntegrationPluginClient is the client API for IntegrationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntegrationPluginClient interface {
	Manifest(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IntegrationPluginManifest, error)
	Deploy(ctx context.Context, in *DeployQuery, opts ...grpc.CallOption) (*DeployResult, error)
	DeployStatus(ctx context.Context, in *DeployStatusQuery, opts ...grpc.CallOption) (*DeployResult, error)
	Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type integrationPluginClient struct {
	cc *grpc.ClientConn
}

func NewIntegrationPluginClient(cc *grpc.ClientConn) IntegrationPluginClient {
	return &integrationPluginClient{cc}
}

func (c *integrationPluginClient) Manifest(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IntegrationPluginManifest, error) {
	out := new(IntegrationPluginManifest)
	err := c.cc.Invoke(ctx, "/integrationplugin.IntegrationPlugin/Manifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationPluginClient) Deploy(ctx context.Context, in *DeployQuery, opts ...grpc.CallOption) (*DeployResult, error) {
	out := new(DeployResult)
	err := c.cc.Invoke(ctx, "/integrationplugin.IntegrationPlugin/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationPluginClient) DeployStatus(ctx context.Context, in *DeployStatusQuery, opts ...grpc.CallOption) (*DeployResult, error) {
	out := new(DeployResult)
	err := c.cc.Invoke(ctx, "/integrationplugin.IntegrationPlugin/DeployStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationPluginClient) Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/integrationplugin.IntegrationPlugin/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationPluginServer is the server API for IntegrationPlugin service.
type IntegrationPluginServer interface {
	Manifest(context.Context, *empty.Empty) (*IntegrationPluginManifest, error)
	Deploy(context.Context, *DeployQuery) (*DeployResult, error)
	DeployStatus(context.Context, *DeployStatusQuery) (*DeployResult, error)
	Stop(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterIntegrationPluginServer(s *grpc.Server, srv IntegrationPluginServer) {
	s.RegisterService(&_IntegrationPlugin_serviceDesc, srv)
}

func _IntegrationPlugin_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationPluginServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrationplugin.IntegrationPlugin/Manifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationPluginServer).Manifest(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationPlugin_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationPluginServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrationplugin.IntegrationPlugin/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationPluginServer).Deploy(ctx, req.(*DeployQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationPlugin_DeployStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployStatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationPluginServer).DeployStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrationplugin.IntegrationPlugin/DeployStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationPluginServer).DeployStatus(ctx, req.(*DeployStatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationPlugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationPluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/integrationplugin.IntegrationPlugin/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationPluginServer).Stop(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _IntegrationPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "integrationplugin.IntegrationPlugin",
	HandlerType: (*IntegrationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Manifest",
			Handler:    _IntegrationPlugin_Manifest_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _IntegrationPlugin_Deploy_Handler,
		},
		{
			MethodName: "DeployStatus",
			Handler:    _IntegrationPlugin_DeployStatus_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _IntegrationPlugin_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrationplugin.proto",
}
