package api

import (
	"context"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/ovh/cds/engine/api/group"
	"github.com/ovh/cds/engine/api/workermodel"
	"github.com/ovh/cds/engine/service"
	"github.com/ovh/cds/sdk"
)

func (api *API) putBookWorkerModelHandler() service.Handler {
	return func(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
		// this handler should only answer to an hatchery
		s, ok := api.isHatchery(ctx)
		if !ok {
			return sdk.WithStack(sdk.ErrForbidden)
		}

		vars := mux.Vars(r)

		groupName := vars["permGroupName"]
		modelName := vars["permModelName"]
		g, err := group.LoadByName(ctx, api.mustDB(), groupName)
		if err != nil {
			return err
		}

		m, err := workermodel.LoadByNameAndGroupID(api.mustDB(), modelName, g.ID)
		if err != nil {
			return sdk.WrapError(err, "cannot load worker model")
		}

		if err := workermodel.BookForRegister(api.Cache, m.ID, s.ID); err != nil {
			return sdk.WithStack(err)
		}

		return nil
	}
}

func (api *API) putSpawnErrorWorkerModelHandler() service.Handler {
	return func(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
		var spawnErrorForm sdk.SpawnErrorForm
		if err := service.UnmarshalBody(r, &spawnErrorForm); err != nil {
			return sdk.WrapError(err, "Unable to parse spawn error form")
		}

		vars := mux.Vars(r)

		groupName := vars["permGroupName"]
		modelName := vars["permModelName"]
		g, err := group.LoadByName(ctx, api.mustDB(), groupName)
		if err != nil {
			return err
		}

		model, err := workermodel.LoadByNameAndGroupID(api.mustDB(), modelName, g.ID)
		if err != nil {
			return sdk.WrapError(err, "cannot load worker model")
		}

		tx, err := api.mustDB().Begin()
		if err != nil {
			return sdk.WithStack(err)
		}
		defer tx.Rollback() // nolint

		if spawnErrorForm.Error == "" && len(spawnErrorForm.Logs) == 0 {
			return nil
		}

		if err := workermodel.UpdateSpawnErrorWorkerModel(tx, model.ID, spawnErrorForm); err != nil {
			return sdk.WrapError(err, "cannot update spawn error on worker model")
		}

		if err := tx.Commit(); err != nil {
			return err
		}

		workermodel.UnbookForRegister(api.Cache, model.ID)

		return service.WriteJSON(w, nil, http.StatusOK)
	}
}

func (api *API) getWorkerModelsEnabledHandler() service.Handler {
	return func(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
		// this handler should only answer to an hatchery
		_, ok := api.isHatchery(ctx)
		if !ok {
			return sdk.WithStack(sdk.ErrForbidden)
		}

		// for an hatchery the token was generated by a admin for all consumer's groups.
		models, err := workermodel.LoadAllUsableWithClearPasswordByGroupIDs(api.mustDB(),
			getAPIConsumer(ctx).GetGroupIDs())
		if err != nil {
			return err
		}

		return service.WriteJSON(w, models, http.StatusOK)
	}
}
