apiVersion: v1
kind: Service
metadata:
  name: {{ template "cds.fullname" . }}-api
  labels:
    app: {{ template "cds.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 8082
    targetPort: grpc
  selector:
    app: {{ template "cds.fullname" . }}-api
