apiVersion: v1
kind: Service
metadata:
  name: {{ template "cds.fullname" . }}-hatchery-k8s
  labels:
    app: {{ template "cds.fullname" . }}-hatchery-k8s
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ template "cds.fullname" . }}-hatchery-k8s
