// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sdk

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson67f3367bDecodeGithubComOvhCdsSdk(in *jlexer.Lexer, out *EventWarningUpdate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "key":
			out.Key = string(in.String())
		case "application_name":
			out.AppName = string(in.String())
		case "pipeline_name":
			out.PipName = string(in.String())
		case "workflow_name":
			out.WorkflowName = string(in.String())
		case "environment_name":
			out.EnvName = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "element":
			out.Element = string(in.String())
		case "created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		case "message_params":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MessageParams = make(map[string]string)
				} else {
					out.MessageParams = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					v1 = string(in.String())
					(out.MessageParams)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "message":
			out.Message = string(in.String())
		case "hash":
			out.Hash = string(in.String())
		case "ignored":
			out.Ignored = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson67f3367bEncodeGithubComOvhCdsSdk(out *jwriter.Writer, in EventWarningUpdate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"application_name\":"
		out.RawString(prefix)
		out.String(string(in.AppName))
	}
	{
		const prefix string = ",\"pipeline_name\":"
		out.RawString(prefix)
		out.String(string(in.PipName))
	}
	{
		const prefix string = ",\"workflow_name\":"
		out.RawString(prefix)
		out.String(string(in.WorkflowName))
	}
	{
		const prefix string = ",\"environment_name\":"
		out.RawString(prefix)
		out.String(string(in.EnvName))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"element\":"
		out.RawString(prefix)
		out.String(string(in.Element))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.Raw((in.Created).MarshalJSON())
	}
	{
		const prefix string = ",\"message_params\":"
		out.RawString(prefix)
		if in.MessageParams == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.MessageParams {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix)
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"ignored\":"
		out.RawString(prefix)
		out.Bool(bool(in.Ignored))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventWarningUpdate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson67f3367bEncodeGithubComOvhCdsSdk(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventWarningUpdate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson67f3367bEncodeGithubComOvhCdsSdk(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventWarningUpdate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson67f3367bDecodeGithubComOvhCdsSdk(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventWarningUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson67f3367bDecodeGithubComOvhCdsSdk(l, v)
}
func easyjson67f3367bDecodeGithubComOvhCdsSdk1(in *jlexer.Lexer, out *EventWarningDelete) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Type":
			out.Type = string(in.String())
		case "Element":
			out.Element = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson67f3367bEncodeGithubComOvhCdsSdk1(out *jwriter.Writer, in EventWarningDelete) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"Element\":"
		out.RawString(prefix)
		out.String(string(in.Element))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventWarningDelete) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson67f3367bEncodeGithubComOvhCdsSdk1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventWarningDelete) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson67f3367bEncodeGithubComOvhCdsSdk1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventWarningDelete) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson67f3367bDecodeGithubComOvhCdsSdk1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventWarningDelete) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson67f3367bDecodeGithubComOvhCdsSdk1(l, v)
}
func easyjson67f3367bDecodeGithubComOvhCdsSdk2(in *jlexer.Lexer, out *EventWarningAdd) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "key":
			out.Key = string(in.String())
		case "application_name":
			out.AppName = string(in.String())
		case "pipeline_name":
			out.PipName = string(in.String())
		case "workflow_name":
			out.WorkflowName = string(in.String())
		case "environment_name":
			out.EnvName = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "element":
			out.Element = string(in.String())
		case "created":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Created).UnmarshalJSON(data))
			}
		case "message_params":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.MessageParams = make(map[string]string)
				} else {
					out.MessageParams = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 string
					v3 = string(in.String())
					(out.MessageParams)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "message":
			out.Message = string(in.String())
		case "hash":
			out.Hash = string(in.String())
		case "ignored":
			out.Ignored = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson67f3367bEncodeGithubComOvhCdsSdk2(out *jwriter.Writer, in EventWarningAdd) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"application_name\":"
		out.RawString(prefix)
		out.String(string(in.AppName))
	}
	{
		const prefix string = ",\"pipeline_name\":"
		out.RawString(prefix)
		out.String(string(in.PipName))
	}
	{
		const prefix string = ",\"workflow_name\":"
		out.RawString(prefix)
		out.String(string(in.WorkflowName))
	}
	{
		const prefix string = ",\"environment_name\":"
		out.RawString(prefix)
		out.String(string(in.EnvName))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"element\":"
		out.RawString(prefix)
		out.String(string(in.Element))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.Raw((in.Created).MarshalJSON())
	}
	{
		const prefix string = ",\"message_params\":"
		out.RawString(prefix)
		if in.MessageParams == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.MessageParams {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.String(string(v4Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix)
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"ignored\":"
		out.RawString(prefix)
		out.Bool(bool(in.Ignored))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventWarningAdd) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson67f3367bEncodeGithubComOvhCdsSdk2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventWarningAdd) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson67f3367bEncodeGithubComOvhCdsSdk2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventWarningAdd) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson67f3367bDecodeGithubComOvhCdsSdk2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventWarningAdd) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson67f3367bDecodeGithubComOvhCdsSdk2(l, v)
}
