// Code generated by protoc-gen-go.
// source: log.proto
// DO NOT EDIT!

/*
Package sdk is a generated protocol buffer package.

It is generated from these files:
	log.proto
	result.proto

It has these top-level messages:
	Log
	Result
*/
package sdk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Log represents an execution log
// Generate *.pb.go files with:
// 	protoc --go_out=plugins=grpc:. ./log.pb.go
// 	protoc-go-inject-tag -input=./log.pb.go
// 	=> github.com/favadi/protoc-go-inject-tag
type Log struct {
	// @inject_tag: db:"id"
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty" db:"id" db:"id"`
	// @inject_tag: db:"pipeline_build_job_id"
	PipelineBuildJobID int64 `protobuf:"varint,2,opt,name=pipelineBuildJobID" json:"pipelineBuildJobID,omitempty" db:"pipeline_build_job_id" db:"pipeline_build_job_id"`
	// @inject_tag: db:"pipeline_build_id"
	PipelineBuildID int64 `protobuf:"varint,3,opt,name=pipelineBuildID" json:"pipelineBuildID,omitempty" db:"pipeline_build_id" db:"pipeline_build_id"`
	// @inject_tag: db:"start"
	Start *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=start" json:"start,omitempty" db:"start" db:"start"`
	// @inject_tag: db:"last_modified"
	LastModified *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=lastModified" json:"lastModified,omitempty" db:"last_modified" db:"last_modified"`
	// @inject_tag: db:"done"
	Done *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=done" json:"done,omitempty" db:"done" db:"done"`
	// @inject_tag: db:"step_order"
	StepOrder int64 `protobuf:"varint,7,opt,name=stepOrder" json:"stepOrder,omitempty" db:"step_order" db:"step_order"`
	// @inject_tag: db:"value"
	Val string `protobuf:"bytes,8,opt,name=val" json:"val,omitempty" db:"value" db:"value"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Log) GetPipelineBuildJobID() int64 {
	if m != nil {
		return m.PipelineBuildJobID
	}
	return 0
}

func (m *Log) GetPipelineBuildID() int64 {
	if m != nil {
		return m.PipelineBuildID
	}
	return 0
}

func (m *Log) GetStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Log) GetLastModified() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Log) GetDone() *google_protobuf.Timestamp {
	if m != nil {
		return m.Done
	}
	return nil
}

func (m *Log) GetStepOrder() int64 {
	if m != nil {
		return m.StepOrder
	}
	return 0
}

func (m *Log) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func init() {
	proto.RegisterType((*Log)(nil), "github.com.ovh.cds.sdk.Log")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xd2, 0x54, 0xb3, 0x8a, 0xca, 0x1c, 0x64, 0x29, 0x82, 0xc1, 0x53, 0x4e, 0x53,
	0xd1, 0xbb, 0x87, 0xd2, 0x4b, 0x45, 0x11, 0x82, 0x27, 0x6f, 0x49, 0x67, 0x9b, 0x2e, 0xdd, 0x74,
	0x96, 0xec, 0xa6, 0xff, 0xcf, 0x7f, 0x26, 0x6e, 0x28, 0x52, 0x29, 0xf4, 0xb6, 0xbc, 0xf7, 0xbd,
	0xe5, 0x1b, 0x91, 0x19, 0x6e, 0xd0, 0x76, 0xec, 0x19, 0x6e, 0x1b, 0xed, 0xd7, 0x7d, 0x8d, 0x4b,
	0x6e, 0x91, 0x77, 0x6b, 0x5c, 0x92, 0x43, 0x47, 0x9b, 0xc9, 0x7d, 0xc3, 0xdc, 0x18, 0x35, 0x0d,
	0x54, 0xdd, 0xaf, 0xa6, 0x5e, 0xb7, 0xca, 0xf9, 0xaa, 0xb5, 0xc3, 0xf0, 0xe1, 0x3b, 0x16, 0xc9,
	0x1b, 0x37, 0x70, 0x25, 0x62, 0x4d, 0x32, 0xca, 0xa3, 0x22, 0x29, 0x63, 0x4d, 0x80, 0x02, 0xac,
	0xb6, 0xca, 0xe8, 0xad, 0x9a, 0xf5, 0xda, 0xd0, 0x2b, 0xd7, 0x8b, 0xb9, 0x8c, 0x43, 0x7f, 0xa4,
	0x81, 0x42, 0x5c, 0x1f, 0xa4, 0x8b, 0xb9, 0x4c, 0x02, 0xfc, 0x3f, 0x86, 0x47, 0x91, 0x3a, 0x5f,
	0x75, 0x5e, 0x8e, 0xf2, 0xa8, 0xb8, 0x78, 0x9a, 0xe0, 0xa0, 0x88, 0x7b, 0x45, 0xfc, 0xdc, 0x2b,
	0x96, 0x03, 0x08, 0x2f, 0xe2, 0xd2, 0x54, 0xce, 0xbf, 0x33, 0xe9, 0x95, 0x56, 0x24, 0xd3, 0x93,
	0xc3, 0x03, 0x1e, 0x50, 0x8c, 0x88, 0xb7, 0x4a, 0x8e, 0x4f, 0xee, 0x02, 0x07, 0x77, 0x22, 0x73,
	0x5e, 0xd9, 0x8f, 0x8e, 0x54, 0x27, 0xcf, 0xc2, 0x15, 0x7f, 0x01, 0xdc, 0x88, 0x64, 0x57, 0x19,
	0x79, 0x9e, 0x47, 0x45, 0x56, 0xfe, 0x3e, 0x67, 0xe9, 0x57, 0xe2, 0x68, 0x53, 0x8f, 0xc3, 0x87,
	0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xab, 0x17, 0x87, 0x97, 0x01, 0x00, 0x00,
}
