// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  sdk

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( WorkflowNodeJobRun ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeJobRun ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeJobRun ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeJobRun ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeJobRun *WorkflowNodeJobRun

func ( WorkflowNodeJobRunInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeJobRunInfo ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeJobRunInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeJobRunInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeJobRunInfo *WorkflowNodeJobRunInfo

func ( WorkflowNodeJobRunSummary ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeJobRunSummary ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeJobRunSummary ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeJobRunSummary ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeJobRunSummary *WorkflowNodeJobRunSummary

func ( WorkflowNodeRun ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRun ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRun ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRun ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRun *WorkflowNodeRun

func ( WorkflowNodeRunArtifact ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunArtifact ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunArtifact ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunArtifact ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunArtifact *WorkflowNodeRunArtifact

func ( WorkflowNodeRunCoverage ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunCoverage ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunCoverage ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunCoverage ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunCoverage *WorkflowNodeRunCoverage

func ( WorkflowNodeRunCoverageTrends ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunCoverageTrends ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunCoverageTrends ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunCoverageTrends ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunCoverageTrends *WorkflowNodeRunCoverageTrends

func ( WorkflowNodeRunHookEvent ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunHookEvent ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunHookEvent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunHookEvent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunHookEvent *WorkflowNodeRunHookEvent

func ( WorkflowNodeRunManual ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunManual ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunManual ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunManual ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunManual *WorkflowNodeRunManual

func ( WorkflowNodeRunRelease ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunRelease ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunRelease ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunRelease ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunRelease *WorkflowNodeRunRelease

func ( WorkflowNodeRunVulnerability ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunVulnerability ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunVulnerability ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunVulnerability ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunVulnerability *WorkflowNodeRunVulnerability

func ( WorkflowNodeRunVulnerabilityReport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeRunVulnerabilityReport ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeRunVulnerabilityReport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeRunVulnerabilityReport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeRunVulnerabilityReport *WorkflowNodeRunVulnerabilityReport

func ( WorkflowNodeTriggerRun ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowNodeTriggerRun ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowNodeTriggerRun ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowNodeTriggerRun ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowNodeTriggerRun *WorkflowNodeTriggerRun

func ( WorkflowRun ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowRun ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowRun ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowRun ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowRun *WorkflowRun

func ( WorkflowRunInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowRunInfo ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowRunInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowRunInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowRunInfo *WorkflowRunInfo

func ( WorkflowRunNumber ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowRunNumber ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowRunNumber ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowRunNumber ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowRunNumber *WorkflowRunNumber

func ( WorkflowRunPostHandlerOption ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowRunPostHandlerOption ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowRunPostHandlerOption ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowRunPostHandlerOption ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowRunPostHandlerOption *WorkflowRunPostHandlerOption

func ( WorkflowRunTag ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* WorkflowRunTag ) UnmarshalJSON([]byte) error { return nil }
func ( WorkflowRunTag ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* WorkflowRunTag ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WorkflowRunTag *WorkflowRunTag
