#!/bin/sh

cd /data

if [ ! -z ${BASE_URL} ]; then
    echo "replace base url with ${BASE_URL}"
    sed -i "s#base.*href.*#base href=\"${BASE_URL}\"\>#" index.html
fi;

cd assets
if [ ! -z ${BUILD_NUMBER} ]; then
    echo "replace base url with ${VERSION}"
    sed -i "s#VERSION#$BUILD_NUMBER#" version.json
fi;

echo "################"
echo "S.T.A.R.T.I.N.G"
echo "################"
cd /data && ./caddy
