// Code generated by MockGen. DO NOT EDIT.
// Source: xray.go

// Package mock_xray is a generated GoMock package.
package mock_xray

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	xray "github.com/ovh/cds/sdk/artifact_manager/artifactory/xray"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetReleaseBundleSBOM mocks base method.
func (m *MockClient) GetReleaseBundleSBOM(ctx context.Context, name, version string) (xray.CycloneDXReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleaseBundleSBOM", ctx, name, version)
	ret0, _ := ret[0].(xray.CycloneDXReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleaseBundleSBOM indicates an expected call of GetReleaseBundleSBOM.
func (mr *MockClientMockRecorder) GetReleaseBundleSBOM(ctx, name, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseBundleSBOM", reflect.TypeOf((*MockClient)(nil).GetReleaseBundleSBOM), ctx, name, version)
}
