package sanity

// Warning unique identifiers
const (
	_ = iota
	MultipleWorkerModelWarning
	NoWorkerModelMatchRequirement
	InvalidVariableFormat
	ProjectVariableDoesNotExist
	ApplicationVariableDoesNotExist
	EnvironmentVariableDoesNotExist
	CannotUseEnvironmentVariable
	MultipleHostnameRequirement
	IncompatibleBinaryAndModelRequirements
	IncompatibleServiceAndModelRequirements
	IncompatibleMemoryAndModelRequirements
	GitURLWithoutLinkedRepository
	GitURLWithoutKey
	EnvironmentVariableUsedInApplicationDoesNotExist
	InvalidVariableFormatUsedInApplication
	MissingEnvironment
)
